# Generated by Django 5.0.6 on 2024-07-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='charge',
        ),
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
        migrations.AddField(
            model_name='room',
            name='mini_description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
