# Generated by Django 5.0.6 on 2024-07-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_rename_price_service_charge_remove_room_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
