# Generated by Django 5.0.6 on 2024-07-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(default='none', max_length=256),
        ),
    ]
