# Generated by Django 5.0.6 on 2024-08-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='employe',
        ),
        migrations.AlterField(
            model_name='employe',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
